<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UpstreamCause>
            <upstreamProject>linoy.2</upstreamProject>
            <upstreamUrl>job/linoy.2/</upstreamUrl>
            <upstreamBuild>18</upstreamBuild>
            <upstreamCauses>
              <hudson.model.Cause_-UpstreamCause>
                <upstreamProject>linoy.1</upstreamProject>
                <upstreamUrl>job/linoy.1/</upstreamUrl>
                <upstreamBuild>37</upstreamBuild>
                <upstreamCauses>
                  <hudson.triggers.TimerTrigger_-TimerTriggerCause/>
                </upstreamCauses>
              </hudson.model.Cause_-UpstreamCause>
            </upstreamCauses>
          </hudson.model.Cause_-UpstreamCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.37-494.v06f9a_939d33a_">
      <queuingDurationMillis>9205</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>1</buildableDurationMillis>
      <waitingDurationMillis>9203</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
  </actions>
  <queueId>79</queueId>
  <timestamp>1775568620103</timestamp>
  <startTime>1775568620110</startTime>
  <result>SUCCESS</result>
  <duration>822</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>C:\Jenkins\workspace\linoy.3</workspace>
  <hudsonVersion>2.528.1</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set"/>
  </culprits>
</build>